import type { SequenceConfig, StorySection, StoryChapter } from "@/types";

/** Generated by scripts/convert-frames.mjs — 182 WebP frames (frame-0000 … frame-0181). */
export const FRAME_COUNT = 182;
export const FRAME_WIDTH = 1280;
export const FRAME_HEIGHT = 720;

export const SEQUENCE: SequenceConfig = {
  frameCount: FRAME_COUNT,
  width: FRAME_WIDTH,
  height: FRAME_HEIGHT,
  getFrameUrl: (index: number) =>
    `/sequence/frame-${String(index).padStart(4, "0")}.webp`,
};

export const HERO_VIDEO = "/video/hero.mp4";

export const BRAND = {
  name: "AURORA",
  product: "PHANTOM ONE",
  tagline: "Sound, sculpted in silence.",
} as const;

/**
 * Story beats overlaid on the pinned frame sequence. Each beat owns a scroll
 * window [start, end] expressed as a 0–1 fraction of the pinned scroll.
 */
export const SEQUENCE_BEATS: ReadonlyArray<
  StorySection & { start: number; end: number; align: "left" | "right" | "center" }
> = [
  {
    id: "reveal",
    kicker: "Phantom One",
    title: "Engineered to disappear",
    body: "A monolith of machined aluminium and acoustic intent — every surface tuned before a single note is played.",
    align: "left",
    start: 0.04,
    end: 0.26,
  },
  {
    id: "driver",
    kicker: "40mm Beryllium",
    title: "The driver, laid bare",
    body: "Beryllium-coated diaphragms move with vanishing inertia, resolving detail the moment it exists.",
    align: "right",
    stat: { value: "5Hz–45kHz", label: "Frequency response" },
    start: 0.38,
    end: 0.6,
  },
  {
    id: "form",
    kicker: "Continuous form",
    title: "Nothing added. Nothing loud.",
    body: "A single sweeping gesture from cup to headband — balance you feel before you hear.",
    align: "left",
    stat: { value: "284g", label: "Total weight" },
    start: 0.72,
    end: 0.96,
  },
];

export const PRODUCT_IMAGE = "/headphone.webp";

/**
 * Persistent-product story. ONE headphone element travels across three pinned
 * chapters; these are the transform targets it eases between (scrubbed). Values
 * are viewport-relative so the composition holds across screen sizes.
 */
export const STORY_CHAPTERS: ReadonlyArray<StoryChapter> = [
  {
    id: "pure",
    index: "01",
    kicker: "Designed for silence",
    title: "Pure Sound",
    body: "It begins with absence. Strip away the world, and what remains is sound in its truest form.",
    align: "left",
    product: { xVW: 18, yVH: 0, scale: 1, rotate: -4 },
  },
  {
    id: "precision",
    index: "02",
    kicker: "Obsessive engineering",
    title: "Engineered Precision",
    body: "Every curve machined to intent. Every gram placed with purpose. Balance you wear without thinking.",
    align: "right",
    product: { xVW: -20, yVH: 2, scale: 0.78, rotate: 6 },
  },
  {
    id: "immersive",
    index: "03",
    kicker: "Total immersion",
    title: "Hear Every Detail",
    body: "The destination of the journey — a single, perfect object, and nothing between you and the music.",
    align: "left",
    product: { xVW: 0, yVH: -1, scale: 1.12, rotate: -2 },
  },
];

export const STORY_SECTIONS: ReadonlyArray<StorySection> = [
  {
    id: "sound",
    kicker: "Premium Sound",
    title: "A stage with no walls",
    body: "Adaptive spatial processing places every instrument in its own pocket of air. Close your eyes and the room dissolves.",
    stat: { value: "360°", label: "Spatial audio" },
  },
  {
    id: "engineering",
    kicker: "Engineering",
    title: "Obsessed with the unseen",
    body: "Forty-one components, machined to micron tolerances, assembled by hand. The complexity exists so the experience never has to.",
    stat: { value: "0.0003%", label: "Total harmonic distortion" },
  },
  {
    id: "materials",
    kicker: "Materials",
    title: "Cold metal, warm touch",
    body: "Aerospace aluminium, memory-foam wrapped in lambskin, and a headband of woven carbon. Luxury you can hold for hours.",
    stat: { value: "40h", label: "Battery, ANC on" },
  },
];
